// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fffxxlobeegrzpdtfsgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmZnh4bG9iZWVncnpwZHRmc2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjU4ODQsImV4cCI6MjA2OTMwMTg4NH0.ym4gQFc3n_23aKfWAdgwAxVGcd86FNBFnhXnCDYRz3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});